version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: discts-backend
    ports:
      - "8080:8080"
    networks:
      - discts-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: discts-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - discts-network

networks:
  discts-network:
    driver: bridge
